Feature/authentication using jwt token
chitranshubisht/user_api pull request #2
Opened 2024-04-24 13:11 UTC by chitranshubisht

```
Added specs for users_controller and posts_controller
Implemented JWT authorization for login
```

2024-04-29 05:17 UTC, nyadav-deqode requested changes

2024-04-29 05:17 UTC, nyadav-deqode commented on .byebug_history
> +params
Why did you push byebug history

2024-04-29 05:17 UTC, nyadav-deqode commented on .byebug_history
> +params
Please update your branch with master

2024-04-29 06:30 UTC, chitranshubisht commented on .byebug_history
> +params
Removed byebug history file.

2024-04-29 06:50 UTC, nyadav-deqode requested changes

2024-04-29 06:50 UTC, nyadav-deqode commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
This will raise an error for other actions like index, create

2024-05-02 05:22 UTC, nyadav-deqode commented on app/controllers/application_controller.rb
> +      render json: { errors: e.message }, status: :unauthorized
Avoid repetition of rescue, make it DRY

2024-05-02 05:24 UTC, nyadav-deqode commented on app/controllers/posts_controller.rb
> +  include JwtToken
This include is repeated in all the controllers, avoid repetition

2024-05-25 18:36 UTC, merged